DatabaseURL: "postgresql://USER:PASSWORD@HOST:PORT/DB_NAME"
OPEN_WEATHER_API_KEY: "XXXXXXXXXXXXXXXXXX"
OPEN_WEATHER_BASE_URL: "https://api.openweathermap.org/data/2.5/weather"
JWT_SECRET: "EXAMPLE"
REFRESH_TOKEN_SECRET: "EXAMPLE"